apiVersion: v2
name: memoryai-enterprise
description: MemoryAI Enterprise - Hyper-personal AI companion with zero-knowledge privacy
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ai
  - memory
  - privacy
  - assistant
  - ml
home: https://memoryai.ai
sources:
  - https://github.com/memoryai/memoryai-enterprise
maintainers:
  - name: MemoryAI Team
    email: team@memoryai.ai
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: prometheus
    version: "23.x.x"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "6.x.x"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled